export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_ITEMS_SUCCESS= ' LOAD_ITEMS_SUCCESS';

export const LOAD_INVENTORIES_SUCCESS = 'LOAD_INVENTORIES_SUCCESS';
export const CREATE_INVENTORY_SUCCESS = 'CREATE_INVENTORY_SUCCESS';
export const UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';

export const LOAD_PRICES_SUCCESS = 'LOAD_PRICES_SUCCESS';

export const LOAD_MEASUREMENTS_SUCCESS = 'LOAD_MEASUREMENTS_SUCCESS';







